version: '3.8'
services:
  turtlebot2:
    build:
      context: .
      dockerfile: turtlebot2_ros2.dockerfile
      args:
        from_image: osrf/ros:iron-desktop
        parallel_jobs: 4
      secrets:
        - env
    image: ingot/turtlebot2-ros-iron:desktop
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/$USER/ros2_ws/robot:/root/robot
    network_mode: host
    stdin_open: true
    tty: true
    command: bash

secrets:
  env:
    file: .env
